### ISSUE TITLE
Live tv, TV series and more not working

### ISSUE THREAD

**Issue by sxoinas** [Twilight0/plugin.video.ert.gr#11]
All sections not working Live tv, all content in tv series, sports, kids etc.

**Comment by Twilight0** [comment]
They 've updated the website, that's why. Will provide update in due time.

**Comment by leotzian** [comment]
The last time ert always update their site, the updated app by the way it became worse that the old one, so we depend on this plugin, but it is not easy for the developers to always update, thank you for what you do, we will wait for your update and I hope that there is no more site update in the near future

**Comment by Twilight0** [comment]
Fixed in 4.0.X+, issue closed.
