### ISSUE TITLE
Documentaries and other folders are not working since last 5 days

### ISSUE THREAD

**Issue by leotzian** [Twilight0/plugin.video.ert.gr#2]
ERT had made some changes to the web interface at https://webtv.ert.gr/tag/ntokimanter/ and other categories, the result of this is that the addon is not giving result when I open folder documentaries etc.
Perhaps a correction to the code must be done.
You can check and yourself
Thanks in advance.

**Comment by Twilight0** [comment]
I am closing this issue, as it has been resolved with the release of 3.0.0 version
