### ISSUE TITLE
Folders Problem

### ISSUE THREAD

**Issue by leotzian** [Twilight0/plugin.video.ert.gr#3]
Folders are not opening to show content and play videos, If you try Foreign Documentaries and choose a category nothing happens because it is a folder category and inside there is the list to choose, in Greek This was working some days ago I don't know what Ert had changed

**Comment by Twilight0** [comment]
ERT's doing changes all the time, I updated it a couple of days ago, now still with issues. Will have look into it.

**Comment by Twilight0** [comment]
I am closing this issue, it has been fixed in version 3.0.3.
