### ISSUE TITLE
ERTFLIX Error on opening Next pages

### ISSUE THREAD

**Issue by leotzian** [Twilight0/plugin.video.ert.gr#5]
Hi and Merry Christmas, there is a bug in ERTFIX, you can check it in Xereta moy ton platano series, but also exist in all series, that has episodes more than one page.
So If you check to see episodes on xereta moy ton platono, there are from Episode 31 till 50, when you press next to see episodes lower than 31 the same page appears. and I have the uploder error on "ERTFLIX.Bug.Error.txt"
This happens in all series in ERTFLIX that has episodes more than one page.
I have the latest ERTFLIX version 3.1.0
Thanks in advance.

[ERTFLIX Bug Error.txt](https://github.com/Twilight0/plugin.video.ert.gr/files/5723612/ERTFLIX.Bug.Error.txt)

**Comment by Twilight0** [comment]
Please disable threading from the settings menu and when the update is released, you can re-enable it. And don't forget to disable debug for now.

**Comment by leotzian** [comment]
Thanks my friend it is working fine now
Merry Christmas
