### ISSUE TITLE
ERT live channels only show ERT 1

### ISSUE THREAD

**Issue by kimondiomis94** [Twilight0/plugin.video.ert.gr#9]
All live channels show live ERT 1

**Comment by Twilight0** [comment]
Fixed by ERTflix webmasters by tweaking their code.

**Comment by kimondiomis94** [comment]
It's doing the same thing again, it only shows Ert1 on all ert live channels

**Comment by Twilight0** [comment]
Issue re-opened as I am also seeing this persisting. Actually the addon's resolver is ok, but for some reason Kodi points directly into ERT 1's worldwide only stream.

**Comment by Twilight0** [comment]
Fixed in 3.5.0.
